// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-t1rUvy_zlMpBJ2CI0amlzlj95j-9pBo',
    appId: '1:814250007597:web:88a1e04d449447396aaca4',
    messagingSenderId: '814250007597',
    projectId: 'shop-demo-a1668',
    authDomain: 'shop-demo-a1668.firebaseapp.com',
    storageBucket: 'shop-demo-a1668.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwjj3Q4sbZmlyBglbuFt8penCiDbRWQ5g',
    appId: '1:814250007597:android:02e141ab16e74ab06aaca4',
    messagingSenderId: '814250007597',
    projectId: 'shop-demo-a1668',
    storageBucket: 'shop-demo-a1668.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9WBHi6wPv-iKlxtNTRrg6AOcgRURgNSg',
    appId: '1:814250007597:ios:df6bc07d0e60483f6aaca4',
    messagingSenderId: '814250007597',
    projectId: 'shop-demo-a1668',
    storageBucket: 'shop-demo-a1668.firebasestorage.app',
    iosBundleId: 'com.example.tuan5',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9WBHi6wPv-iKlxtNTRrg6AOcgRURgNSg',
    appId: '1:814250007597:ios:df6bc07d0e60483f6aaca4',
    messagingSenderId: '814250007597',
    projectId: 'shop-demo-a1668',
    storageBucket: 'shop-demo-a1668.firebasestorage.app',
    iosBundleId: 'com.example.tuan5',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-t1rUvy_zlMpBJ2CI0amlzlj95j-9pBo',
    appId: '1:814250007597:web:01101b972d22205c6aaca4',
    messagingSenderId: '814250007597',
    projectId: 'shop-demo-a1668',
    authDomain: 'shop-demo-a1668.firebaseapp.com',
    storageBucket: 'shop-demo-a1668.firebasestorage.app',
  );
}
